### ISSUE TITLE
default access level for new groups is ignoring the overall privacy level of the group (elgg 1.12.x)

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/group_tools#101]
1. set the default privacy level for groups using the group tools admin page to 'public'.
2. create a new group that is closed (private).
3. the default privacy level for content created in the closed group is apparently 'public'.

i thought that it would be impossible for closed groups to hold public items, but that apparently isn't the case. i would call that a bug, but the complexity of the various plugins in use means that i don't know exactly where the fix should go.

**Comment by jdalsem** [comment]
The group tools access setting has been removed a few years ago https://github.com/ColdTrick/group_tools/commit/eb27b60c6c17516e0425698144521d13ae7d2380#diff-89c424c6b5df225009727d6b086f1848d888d9b6fcaece0250d121e72b58afe4
