### ISSUE TITLE
"related group" feature broken by "elgg_tokeninput" plugin

### ISSUE THREAD

**Issue by oseg** [ColdTrick/group_tools#102]
"related group" feature broken by "elgg_tokeninput" plugin

Scenario:
1. Create a group with the "show related groups" option selected
2. Go on the "related groups" page to add a new related group
3. Enter the first letters of the group name in the related groups field -> autocomplete suggests the corresponding group full name
4. Click on the suggestion, the group name is displayed in the field
5. Validate by clicking on the add button
=> a "page not found" Error message is displayed when trying to execute the following url action: http://localhost/elgg/action/group_tools/related_groups

There is probably a conflict around the autocomplete: if "elgg_tokeninput" is deactivated, in step 4, the group guid is displayed in the field (not the group name).

It happens on both:
elgg v2.1.1 with group_tools v7 and elgg_tokeninput v4.1.0
elgg v1.12.9 with group_tools v6.0.2 and elgg_tokeninput v3.3.2

I will also create an issue on elgg_tokeninput side.

Olivier

**Comment by oseg** [comment]
elgg_tokeninput issue created:
https://github.com/hypeJunction/elgg_tokeninput/issues/7

**Comment by hypeJunction** [comment]
You can close this. I have fixed the issue.

**Comment by oseg** [comment]
Issue not reproduced with elgg v2.1.1, group_tools v7 and elgg_tokeninput v4.1.1
