### ISSUE TITLE
"$num_replies" displayed in groupforumtopic view rather than number itself

### ISSUE THREAD

**Issue by oseg** [ColdTrick/group_tools#103]
Small regression introduced in v6.0

Potential fix: in views/default/object/groupforumtopic.php (line 69)
```
-		'text' => elgg_echo('group:replies') . ' ($num_replies)',
+		'text' => elgg_echo('group:replies') . " ($num_replies)",
```

Olivier

**Comment by jeabakker** [comment]
this is already fixed in 03e8d10389c5597a9e38d429f3ceb18f6d0be5a8 but no new release yet

**Comment by oseg** [comment]
Oups sorry, I didn't look at the latest commit...
Is a new release of v6.0 planned soon, or should I use the latest code of the elgg_111 branch?

**Comment by jeabakker** [comment]
i'll look into creating a new 6.x release Soon(TM)

**Comment by oseg** [comment]
Thanks
