### ISSUE TITLE
cannot access 'create new group' page when group_tools is active

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/group_tools#108]
in both the current release of group_tools and the previous one i am unable to allow non admins to create groups. they see the warning message pop up that states that they cannot view that page.
if i disable group_tools then the page loads correctly.
i have disabled my theme and all other plugins that i think/know may interact with groups in a relevant way, but still haven't found the cause of the issue.

**Comment by propertunist** [comment]
i looked into the code for this and this function call is returning 'true' for me when it shoudn't:
```
elgg_get_plugin_setting('admin_create', 'group_tools'))
```
as a result, the admin gatekeeper is called in the group tools router and the page load is denied. maybe 'admin_create' was an option in an earlier version of group_tools in the admin area and it has been removed - but my site still has a value saved for it in the database?

**Comment by jeabakker** [comment]
you found a legacy bug! A long time ago groups (from Elgg core) added the option to set group creation to admins only.
I then removed the settings related to that, but forgot to rewrite a function

Thanks for reporting

**Comment by propertunist** [comment]
no problem, thanks for fixing! greetings from here! :)
