### ISSUE TITLE
invite friends via username search and email fails

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/group_tools#110]
with group tools v.7.3 in elgg 2.1, when i type a username or an email in the relevant input fields to search for a user to invite to a group, i just see a small, empty dropdown field appear and have no way to actually search for or add a user to the list of invitations.

**Comment by jeabakker** [comment]
do you get any JS errors on the page? I'm having a hard time reproducing it

**Comment by propertunist** [comment]
i'm not seeing any JS errors in firefox, but in chromium i see:
```
Uncaught TypeError: Cannot read property 'menu' of undefined
```

**Comment by jeabakker** [comment]
any other plugins that could be interfering? for me both FF and Chrome don't give any problems :(

**Comment by propertunist** [comment]
found it! the issue is a conflict with pagehandler hijack. if i enable that plugin and change the handler for 'groups' (which i have done since i use 'zones' instead) - then this bug occurs.

**Comment by jeabakker** [comment]
I think i can't fix this issue. Maybe if @beck24 makes his plugin use the 'route:rewrite' (added in 2.1 https://github.com/Elgg/Elgg/pull/9390) hook the problem isn't there anymore.

**Comment by propertunist** [comment]
ok, i'll open an issue on pagehandler hijack, thanks.
