### ISSUE TITLE
receiver in the admin transfer process needs a method of accept/reject

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/group_tools#111]
presently, it is possible for admins to transfer ownership of groups to other people, yet those people have no say in whether they will be the admin or not. this violates principles of free will ;)
in sites that have no form of approval for new zones this would mean that i can create 50 new groups and then transfer them all to other people, without them knowing i am going to do it. although that would be a malicious waste of time, it would be better if there was an option for the nominated admin to be able to accept or reject the role.

**Comment by jdalsem** [comment]
We see it as a feature that an ADMIN can do this without any interference. We will not add this as a feature.
