### ISSUE TITLE
Group Approval Notification to Multiple Admin

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/group_tools#112]
I have 3 admin in my elgg (2.2.2). I have the enabled the new groups require admin approval setting.

My issue is that the group approval mail is going to only 1 out of the 3 admins. Rest of the admins are not getting notified.

**Comment by jeabakker** [comment]
An admin will only receive a notification if their personal notification settings are configured.
![naamloos](https://cloud.githubusercontent.com/assets/881958/20001592/39951b18-a27d-11e6-8e15-955ca0559fee.png)

If both are off they won't receive a notification
