### ISSUE TITLE
Count all notify relationships for enable/disable notifications

### ISSUE THREAD

**Issue by Wouter0100** [ColdTrick/group_tools#114]
Instead of only counting `notifyemail` and maybe `notifysite`, why not count all `notify*`s? (see here https://github.com/ColdTrick/group_tools/blob/ac63a651cafba8178acceb7aa0ad9b8b14f7d231/views/default/group_tools/forms/notifications.php#L21-L42) This should be a more reliable count, as we've disabled all e-mail and site notifications and created a custom one.

**Comment by jeabakker** [comment]
yes this could use some rework, this was the easy solution.

It should also not do a count, but make sure to check the users. because if someone has one method disabled and the other method has a higher count it doesn't count that user.

This would lead to more db-queries though....

**Comment by Wouter0100** [comment]
One query should do the trick: `SELECT COUNT(id) FROM elgg_entity_relationships WHERE relationship LIKE 'notify%' AND guid_two = {group ID} GROUP BY guid_one`. 

Only I don't know how to do this the Elgg-way.

**Comment by jeabakker** [comment]
> One query should do the trick: SELECT COUNT(id) FROM elgg_entity_relationships WHERE relationship LIKE 'notify%' AND guid_two = {group ID} GROUP BY guid_one.

that would result in a custom query, i'd like to avoid that and do it the Elgg way.... ;)

**Comment by Wouter0100** [comment]
Yeah, unfortunately Elgg doesn't have a real powerful ORM yet, so I guess then you should make much queries..

**Comment by jeabakker** [comment]
fixed in e5a4ab34f5ce56d0d308f6fdd467a1423376e19c i think
