### ISSUE TITLE
Reset notifications to defaults, instead of site and email

### ISSUE THREAD

**Issue by Wouter0100** [ColdTrick/group_tools#115]
Currently when you click [this](https://github.com/ColdTrick/group_tools/blob/ac63a651cafba8178acceb7aa0ad9b8b14f7d231/views/default/group_tools/forms/notifications.php#L50-L57) button, you enable site and email notifications. Shouldn't it be better to reset it in this case to the configured notifications in the backend?

**Comment by jeabakker** [comment]
you mean the default group notification methods on the plugin settings? Good idea

**Comment by Wouter0100** [comment]
Exactly, currently it assumes you still use site and email notifications, regardless of this default setting.
