### ISSUE TITLE
feature/suggetion group invitation should automatically join the group after registration

### ISSUE THREAD

**Issue by dipenpatel235** [ColdTrick/group_tools#125]
hello..
i am inviting friend so facing below issue..

1. after invite friend user registration forum in email not auto filled. or not required that field.
2. after registration again required to confirm email address
3. invited user should automatically join the group after registration 

can u please help me to full fill above 3 issue.

Thanks

**Comment by jeabakker** [comment]
> after invite friend user registration forum in email not auto filled. or not required that field.

This is just part of Elgg core. And who says your friend want to register with the email address you invited him on. Maybe he wants to register with a different one.

> after registration again required to confirm email address

This is part of the 'user validation by email' plugin

> invited user should automatically join the group after registration

If the user was invited from the group and register with the same e-mail address as invite this is already the case
