### ISSUE TITLE
issue in elgg email invite user

### ISSUE THREAD

**Issue by dipenpatel235** [ColdTrick/group_tools#126]
hello..
i am trying ti invite my friend via email to my group.
but for that after 3 hour spent then i get idea to hit enter after write email in email box.

so no one user easily know to hit enter after write email in the box.

so instead of can you do to used that box email address or something better what you like as per your thought?

thanks

**Comment by jeabakker** [comment]
the text of the input field says `Enter a valid e-mail address and select it from the list` i think that's clear enough

**Comment by dipenpatel235** [comment]
Yes that is clear i know..
but i don't think normal user can able to under stand and user friendly .

Because about that i have complain 3-4 user Out of 7 user.

Thanks
