### ISSUE TITLE
No river item '<newuser> joined the group <mygroup>' on siteJoinDomainBasedGroups

### ISSUE THREAD

**Issue by oseg** [ColdTrick/group_tools#127]
Context: elgg v2.3.3 + group_tools v9.2.2
Scenario:
- In group tools plugin settings, set 'Enable domain based groups' to 'yes'
- In 'mygroup' 'other option' settings, add 'mydomain.com' in the 'Configure e-mail domains' list
- A 'newuser' whose email is 'newuser@mydomain.com' register to the elgg site

'newuser' automatically joins 'mygroup' group, but there is no " 'newuser' joined the group 'mygroup' " activity event in the group or in the site activity.

**Comment by oseg** [comment]
Same issue with other scenarios: 

Issue reproduced on siteJoinEmailInvitedGroups().

I did not test autoJoinGroupsCron(), autoJoinGroupsLogin(), siteJoinGroupInviteCode(), but these functions are also calling "$group->join($user)" without creating the river event. Then the issue could also be reproduced.

**Comment by jeabakker** [comment]
It's a choice we made to not create the river items for all the groups a new user joins automatically. 

Because with all the different options a user can join many groups at once, so this would flood the activity page.

**Comment by oseg** [comment]
Ok, I understand, but my closed group owners did not;-) They asked me, why these river events were missing in both the activity views and digest emails...

**Comment by jdalsem** [comment]
> It's a choice we made to not create the river items for all the groups a new user joins automatically.
