### ISSUE TITLE
Inconsistency between 'group activity' view and 'group activity' widget

### ISSUE THREAD

**Issue by oseg** [ColdTrick/group_tools#129]
Context: elgg v2.3.3 + group_tools v9.2.2 + widget manager v8.1

Scenario:
- In the widget manager plugin settings, set 'Enable Widget Manager for groups' to 'yes, always on'
- Create an open group called 'mygroup'
- In the 'mygroup' profile page, add the 'group activity' widget
- 'user A' joins 'mygroup'

==> in the 'group activity' widget, "'user A' joined the group 'mygroup'" is displayed
However, in the group activity view, nothing is displayed about 'user A' who joined 'mygroup'...

**Comment by oseg** [comment]
I noticed another inconsistency: in the 'group activity' widget, the comments are not displayed, whereas they are displayed in the 'group activity' view

**Comment by jeabakker** [comment]
this is fixed in Elgg 3.0 by https://github.com/Elgg/Elgg/pull/12286
