### ISSUE TITLE
Missing mail params in notify_user() on transferring group ownership or adding a related group

### ISSUE THREAD

**Issue by oseg** [ColdTrick/group_tools#131]
Context: elgg v2.3.3 + group_tools v9.2.2

Same kind of issue as #118, but with other scenarios:
- Transferring ownership of a group
- Adding a related group

Side effect: Makes notifier plugin crash (juho-jaakkola/elgg-notifier#33)

**Comment by jeabakker** [comment]
fixed in 827c4d1660401ce83ed21c0fc4682ca7d6a8c6a9
