### ISSUE TITLE
Lost font awesome icon in owner block menu

### ISSUE THREAD

**Issue by nfortea** [ColdTrick/group_tools#132]
Hi,
I have trouble showing fontawesome icon in owner block menu.
Somebody can help?

**Comment by jeabakker** [comment]
Are you trying to add a FontAwesome icon to a Group Tools menu item? I don't understand how this is related to the Group Tools plugin

**Comment by nfortea** [comment]
Hi,
When I am in a group, I can see a menu with active tools in the sidebar.
Each menu item has an icon except for the "related groups" element created by Group Tools.

**Comment by jeabakker** [comment]
Are you using a development version of Elgg 3.0? is so group tools is not done yet ;)

**Comment by nfortea** [comment]
No. We are working with Elgg 2.3.

**Comment by jeabakker** [comment]
> No. We are working with Elgg 2.3.

then probably the icons are added by your theme, and it should add support for the related groups menu item https://github.com/ColdTrick/group_tools/blob/master/classes/ColdTrick/GroupTools/OwnerBlockMenu.php#L29

**Comment by jdalsem** [comment]
Closing this issue as the relation with the group tools plugin is unclear
