### ISSUE TITLE
Auto join: unable to add user automatically on hidden group based on profile field (user properties)

### ISSUE THREAD

**Issue by rheman** [ColdTrick/group_tools#133]
Hi,
I am trying to auto join to add user on group based on profile field (user properties)
- When the group is defined as open group, everything works perfectly and users auto join the group base on his profile field.
- When the group is defined as closed group, nothing happen. The user does not joint the group based on his profile field.

How can I do i order to allow user to auto join closed group ?

Best regard

**Comment by jdalsem** [comment]
it should be possible. I see no logic in the code that prevents this. Did you try to debug this?

**Comment by rheman** [comment]
yes I try to debug this. but nothing in the log file

**Comment by jeabakker** [comment]
- Which version of Elgg and Group Tools are you using?
- Does this only apply to new users who login before they are joined to groups (< 5 minutes after creating a new user account)
