### ISSUE TITLE
"Mail Members" not working

### ISSUE THREAD

**Issue by reimerd** [ColdTrick/group_tools#141]
I posted about this on the [Elgg.org "tech support"][e] group, but didn't get any replies, so I'm trying here ... and living in hope! This is what I reported there:

This is an odd one. Emails sent from the "Mail members" feature added by the `group_tools` plugin do not arrive at the intended members. Here's what I've observed (so far):

- the number of members targetted for the email is correctly displayed;
- having clicked the "Send" button, a success message is echoed: "Message successfully send";
- in the Administration Dashboard, the "Content statistics" displays the correct number of "Group mail" uses;
- BUT ... **no users receive the email**.
- It makes no difference if the WHOLE group is selected for mailing, or whether certain ones (or just one) is selected, or whether the group admin is included or not.
- However, emailed notifications are working correctly (so it seems the server has no problems generating and sending mails).
- I get the identical results on two different installations of Elgg on two different servers.

On our production site, we are using Elgg 2.3.8 on a (virtual) server running PHP 7.0. I've looked in the "Group tools" issue list, and can't see anyone else having this problem. (My test site runs the same Elgg version, but under PHP 5.6.)

Help diagnosing this problem (or even better, fixing it!) would be appreciated. I've looked at all the settings I can think of to look at, but can't spot anything amiss -- but I'm well aware that I've got a lot still to learn about Elgg and its ways! Thanks.

(By the way: I see that issue #65 involves mailing members, but I don't know if that issue and linked commits are related to my problem.)

[e]: https://elgg.org/discussion/view/2815275/mail-members-not-working-part-of-group-tools-plugin

**Comment by jeabakker** [comment]
The GroupMail feature uses the same logic as other content creation notification (eg a new blog was created).

If the number of group mails in the stats only keeps going up that's a bad thing, as at the end of sending the notifications the GroupMail object is removed from the database.

Does the error_log file show anything? Processing is done in the minute cron, so around whole minutes you should look in the error_log

**Comment by nlybe** [comment]
I thought I had the same issue but finally it work if enable the minute cron. 
It's just not clear that the mail function works as content creation notification and cron is required to be enabled, so it quite confusing. I suggest you add a comment on plugin settings.

Thanks

**Comment by jeabakker** [comment]
I'll look if i'll add some documentation to the Group Mail functionality. However not having cron setup on your Elgg installation makes a lot of stuff not working, so that's why i assume site administrators have this configured.

**Comment by reimerd** [comment]
This fills me with hope! But I have no idea *what* I should set up as a cron job for this to work on my server. I have the Webmin/Virtualmin site admin, and [know where][1] to set up [cron jobs][2], but really no idea what @nlybe might have done to get this working.

It would be great, @jeabakker, if there was a bit of documentation on this specific to Group Tools to supplement the main [Elgg docs][3]. Thanks so much!

[1]: https://www.virtualmin.com/documentation/tutorial/how-to-setup-a-cron-job
[2]: https://doxfer.webmin.com/Webmin/Scheduled_Cron_Jobs
[3]: http://learn.elgg.org/en/stable/admin/cron.html

**Comment by dajare** [comment]
I haven't yet been able to work out how to apply Elgg doc directions on setting up `cron` in my Webmin context ... **but**! I did discover the [Crontrigger plugin][c] by @iionly which does the job just fine. Hopefully I'll work it out "properly", but in the meanwhile, this solution works! Phew.

[c]: https://elgg.org/plugins/2512029

**Comment by reimerd** [comment]
I haven't yet been able to work out how to apply Elgg doc directions on setting up `cron` in my Webmin context ... **but**! I did discover the [Crontrigger plugin][c] by @iionly which does the job just fine. Hopefully I'll work it out "properly", but in the meanwhile, this solution works! Phew.

[c]: https://elgg.org/plugins/2512029
