### ISSUE TITLE
"Hide the group members" in sidebar cleanup does not work

### ISSUE THREAD

**Issue by iionly** [ColdTrick/group_tools#143]
Group member widget still shows up regardless if this option is enabled or not.

**Comment by jdalsem** [comment]
in Elgg 3.x or in 2.3

**Comment by iionly** [comment]
Version 9.4 of group_tools on Elgg 2.3.10.

**Comment by jdalsem** [comment]
you are aware this cleanup involves the sidebar module of members... not the 'widget'?

**Comment by iionly** [comment]
Yes... sidebar.

But on testing again just now I found out what I missed before! It says clearly "This will have no effect for the group admins." Doh! I had just tested as admin. Logged in as regular member the sidebar is indeed no longer showing the group members module. So, there's no issue to fix after all.
