### ISSUE TITLE
Scalibility of group edit with regards to members of groups

### ISSUE THREAD

**Issue by iionly** [ColdTrick/group_tools#144]
It looks like it takes much longer on groups with many members to load the group edit page. Maybe the loading time is connected with the notification settings options on the Other Options tab, i.e. the more members the longer it takes to check notification settings. On really large groups this could become a problem.

**Comment by jeabakker** [comment]
I think it's mostly group admin transfer which shows a select with all group members!!!!??? This is changed in Elgg 3 to a userpicker.

Notification settings just does a few count queries, so shouldn't be too hard.

**Comment by iionly** [comment]
Neither notification settings nor group admin transfer (I had this option turned off). It turned out to be a side-effect of overriding access.php of group_tools within the loginrequired plugin - especially with the access.php used in loginrequired not matching core access.php. With https://github.com/ColdTrick/group_tools/issues/142 fixed by correctly overriding access.php the group edit page loaded fast also with several thousand group members.
