### ISSUE TITLE
Cannot register into a wall garden site even through an invitation

### ISSUE THREAD

**Issue by oseg** [ColdTrick/group_tools#148]
Context: 
- elgg v3.2.0 + group_tools v10.4
- site settings: 
  - disable "allow visitors to register"
  - enable "restrict pages to logged-in users"
- group_tools settings:
  - Allow all users to be invited by e-mail address

Scenario:
- Create a 'test' group
- Click on 'test' group 'invite user' button
- Enter the email address of the user to invite, click "add" and "invite" buttons
  => invitation is sent
- The invited user receives the email invitation and he clicks on the registration hyperlink
- On the registration page, he entered the mandatory fields (Display name...) and click "register" button

Results:
- The "Registration has been disabled by the system administrator" error message is displayed

Expected results:
- A successful registration message

Note:
- It uses to work in elgg v2.3.14 + group_tools v9.4

**Comment by jeabakker** [comment]
I'm unable to reproduce this currently (master). 
I checked the code and I don't see that I touched any of the code related to the e-mail invitations.

I followed the steps above and my test user could register and was added to the invited group.

**Comment by oseg** [comment]
I will update my codebase (elgg+group tools) and let you know if I reproduce the issue

**Comment by jdalsem** [comment]
Current codebase works as expected
