### ISSUE TITLE
[Feature request] who invited who information for site and group admins in members list

### ISSUE THREAD

**Issue by oseg** [ColdTrick/group_tools#149]
In wall garden site and/or closed groups, it would be nice for the site and group admins to know if a member has been invited and by who (and when) just by looking in the members list.

**Comment by jeabakker** [comment]
As of Elgg 3.2 the "who has been invited and when" is already handled

Members:
![Schermafbeelding 2019-11-20 om 14 49 24-fullpage](https://user-images.githubusercontent.com/881958/69244365-2070e380-0ba5-11ea-8bc7-c118b73a1b64.png)

Emails:
![Schermafbeelding 2019-11-20 om 14 49 29-fullpage](https://user-images.githubusercontent.com/881958/69244395-2d8dd280-0ba5-11ea-8068-cd45373ad6b8.png)

Just the "by who" isn't handled and currently there is no way to track this information without loss of functionality.

**Comment by oseg** [comment]
That's good news for Elgg v3.2.

But about the "by who", I don't see the blocking issue... Let me suggest something:

We could:
1- make evolve the 'email_invitation' annotation to keep the invitation sender information, as the annotation owner.
2- replace the 'invited' relationship by an 'invitation' group annotation similar to 'email_invitation'
3- On group join, before deleting the 'invitation' and 'email_invitation' annotations, we could get the sender information and create another group annotation called 'invited_by' for instance.
4- It will of course require some invitation migration script

What do you think ?

**Comment by jeabakker** [comment]
> make evolve the 'email_invitation' annotation to keep the invitation sender information, as the annotation owner.

What if the inviting user get deleted. All his/her annotations are also removed, thus no more invitation can be validated for the invited user.....

> replace the 'invited' relationship by an 'invitation' group annotation similar to 'email_invitation'

This is how Elgg core handles user invites, would therefor require rewrite of Elgg core feature. Plus still have the same issue as mentioned above when removing the user

**Comment by oseg** [comment]
Good point, I didn't think about that. But if the inviting user is deleted, he won't be anymore a member of the group, so it makes sense to delete his/her group invitations or not (debate question).

Yes, it will require some core enhancements. But I think it worth it. It's a pity to have the inviting user information, using it in the notification and lose it afterwards.

**Comment by jdalsem** [comment]
We are accepting the current situation
