### ISSUE TITLE
Select users options don't work on the Mail members page

### ISSUE THREAD

**Issue by RiverVanRain** [ColdTrick/group_tools#155]
**Elgg version**
Elgg 3.3.4

**Plugin version**
12.0.2

**Plugin source**
- Github releases download

**Describe the bug**
Select users options don't work on the Mail members page

**To Reproduce**
1. Go to 'Mail Members' page of the group
2. Click on 'Clear selection' button then 'All members'
3. Or try to select individual users.
4. 'Number of recipients' is always '0'

**Additional context**
https://elgg.org/discussion/view/3050764/trouble-using-group-mail

**Comment by chrzimmer** [comment]
is there any chance for a quick fix i could do ? Currently it hurts me very much ...
