### ISSUE TITLE
Cannot save 'Group activity' widget in the Dashboard page on Elgg3.3.8

### ISSUE THREAD

**Issue by Ngseri** [ColdTrick/group_tools#158]
**Elgg version**
Elgg3.3.8

**Plugin version**
12.0.3

**Plugin source**
- Git clone https://github.com/ColdTrick/group_tools.git

**Describe the bug**
saveSettings() in wwwroot/vendor/elgg/elgg/engine/classes/ElggWidget.php accepts only one layer array. Check the line 272.
But mod/group_tools/views/default/widgets/group_river_widget/edit.php creates multi array. This is as example of value I printed out - _**Array( [num_display] => 4,    [activity_filter] => 0,   [group_guid] => Array([0] => 168xxx ))**_

**To Reproduce**
1. Go to Dashboard
2. Click on 'Add widgets' and add 'Group Activity'
3. Click the gear icon at the top right of the 'Group Activity' widget
4. Fill out the 'Group Activity' form and click 'Save'
5. Error appears at the top right of the page 'Could not save your widget'

**Comment by jeabakker** [comment]
Confirmed, I was trying to find out what i meant by this:
https://github.com/ColdTrick/group_tools/blob/a2b8ffa81c45f4452a7343349a1b0fc71f9ed4a1/elgg-plugin.php#L120-L123

Maybe we lost a hook which could correct the issue

**Comment by jdalsem** [comment]
this widget requires the widget_manager plugin to be able to save arrays to widgets

**Comment by Ngseri** [comment]
Thanks jeabakker and jdalsem!
