### ISSUE TITLE
Failure saving Group activity widget on the User dashboard

### ISSUE THREAD

**Issue by RiverVanRain** [ColdTrick/group_tools#160]
**Elgg version**
Elgg 3.3.17

**Plugin version**
12.0.6

**Plugin source**
- Github releases download

**Describe the bug**
Unable to save Group activity widget's settings on the user's Dashboard page.

**To Reproduce**
1. Go to **Dashboard**
2. Click on **Add widget**
3. Choose **Group activity**
4. Try to select any group and click on **Save**
5. **We could not save your widget** error message will appear

**Expected behavior**
This happens when the **Widget manager** plugin is deactivated or activated.
No any third party plugins.

**Comment by jeabakker** [comment]
I'm unable to reproduce the problem.

Do you have any errors in the error log that could help me?

**Comment by RiverVanRain** [comment]
I've checked again and noticed that it's happening with _autocomplete input_ mode.
I don't know where it comes from; I'll investigate this.

Again, no 3-rd party plugins, or core's changes.

> Do you have any errors in the error log that could help me?

No errors.


https://user-images.githubusercontent.com/2176145/115240988-fa989700-a128-11eb-80ab-38c4f699b781.mp4

**Comment by RiverVanRain** [comment]
Nevermind. Found that my issue is related with some odd caching on the server.
Fixed already.
