### ISSUE TITLE
Configure -> Groups causes the groups plugin settings menu item to disappear

### ISSUE THREAD

**Issue by jeabakker** [ColdTrick/group_tools#161]
**Elgg version**
3.3

**Plugin version**
master

**Describe the bug**
With group tools enabled the link under Plugin settings to the Groups settings page disappears.
Because of duplicate menu item name
https://github.com/ColdTrick/group_tools/blob/3e7df6ec4827caaa8af548251c323edd77a02a2a/classes/ColdTrick/GroupTools/PageMenu.php#L25

**Comment by jdalsem** [comment]
Fixed in core by https://github.com/Elgg/Elgg/commit/cbe3ef6deea6ca758e0b320a0e8d482137359db6
