### ISSUE TITLE
Fatal error creating a concept group

### ISSUE THREAD

**Issue by RiverVanRain** [ColdTrick/group_tools#162]
**Elgg version**
3.3.20

**Plugin version**
12.2

**Plugin source**
- Github releases download

**Describe the bug**
A fatal error occurs when creating a concept group:

> ELGG.CRITICAL: 
> Error: Call to a member function getParentName() on null in \mod\group_tools\classes\ColdTrick\GroupTools\TitleMenu.php:307

**To Reproduce**
1. Click on 'Create a new group'
2. Fill a form.
3. Click on 'Save as draft'.
4. Redirect to the page of the newly created group
5. See error

Same if you just go to the page of any concept group

**Comment by jeabakker** [comment]
thanks for reporting, i fixed it in 12.2.1
