### ISSUE TITLE
Group listing pagination

### ISSUE THREAD

**Issue by poVoq** [ColdTrick/group_tools#51]
The group listing pages of "latest discussions" and "ordered" seem to be lacking pagination, thus with a lot of discussions or groups these get really big.

"ordered" also seems to be not very clearly labled as all it seems to do is to list the groups as "newest", right?

**Comment by jdalsem** [comment]
Latest discussion is just a long list (pagination starts after 40 items). 

The ordered tab will show the same as newest, but has the ability to order (drag and drop) the groups. This feature is primarily meant for smaller communities (at least with a short list of groups). The ordered tabs shows all groups, so there is no pagination.
