### ISSUE TITLE
Group Mail OOM with many members

### ISSUE THREAD

**Issue by beck24** [ColdTrick/group_tools#65]
The group mail form gets all members of the group from the database.  This isn't scalable.  Suggest entity picker to select individual recipients with default to all members.  Have send action run in the background to prevent timeouts (using vroom for example)

**Comment by jeabakker** [comment]
I haven't figured out a good way to replace the friendspicker as is has some usefull features that the userpicker doesn't have (eg. all members beginning with letter x), also the userpicker can't be limited to the group members.

**Comment by jeabakker** [comment]
fixed in f71f55a94b51a735452b1093abd41bacf56f32f0
