### ISSUE TITLE
I tried upgrading to group tools, but after insta

### ISSUE THREAD

**Issue by siteleas** [ColdTrick/group_tools#78]

**Comment by jdalsem** [comment]
there is some info missing in this issue.. can you add that?

**Comment by siteleas** [comment]
After I installed your plugin (it looks like it will be good once I can get it working), all group photos show the name of the group rather than the photo. The photo is missing.

**Comment by jdalsem** [comment]
i guess you are using Elgg 1.10?

**Comment by siteleas** [comment]
Yes, that's correct

On February 4, 2015 2:00:30 AM MST, Jeroen Dalsem <notifications@github.com> wrote:
>i guess you are using Elgg 1.10?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ColdTrick/group_tools/issues/78#issuecomment-72812245

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jdalsem** [comment]
there is a know issue with some of our plugins related to a core change in 1.10 that breaks part of this plugin. You can expect a fix for it soon.

**Comment by siteleas** [comment]
I am very excited about your fix

On February 4, 2015 2:24:11 AM MST, Jeroen Dalsem <notifications@github.com> wrote:
>there is a know issue with some of our plugins related to a core change
>in 1.10 that breaks part of this plugin. You can expect a fix for it
>soon.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ColdTrick/group_tools/issues/78#issuecomment-72819451

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by siteleas** [comment]
Also, I am just starting to develop for elgg, do you have any advice on how to avoid pitfalls. Or tips or tools to make developing themes and other plugin development for elgg more trouble free?

On February 4, 2015 2:24:11 AM MST, Jeroen Dalsem <notifications@github.com> wrote:
>there is a know issue with some of our plugins related to a core change
>in 1.10 that breaks part of this plugin. You can expect a fix for it
>soon.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ColdTrick/group_tools/issues/78#issuecomment-72819451

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jdalsem** [comment]
You can see the solution being discussed here: https://community.elgg.org/plugins/736791/releases/3.0 (about the EntityDirLocator). The fix on github will have to wait until @jeabakker is available to work on it. That won't be the case for the next 2 weeks.

**Comment by siteleas** [comment]
Thanks for the update.

**Comment by siteleas** [comment]
I don't know why Elgg keeps breaking their developers plugins. If a person has gone to great effort to make a plugin, then in each subsequent version it gets broken again, that seems very poor. They should make every change very clear with examples given in each case for upgrading every item that is depreciated. They make it very hard for people (it seems to me).

**Comment by jdalsem** [comment]
Elgg is not breaking things, but plugin developers sometimes choose to use private functions of Elgg for their plugins. It gets things done, but it has the risk of stuff like this. When a plugin developer is using too much private features of Elgg core, then maybe he/she should request a public version of that function. You can see a similar discussion here: https://github.com/Elgg/Elgg/issues/7838

**Comment by jeabakker** [comment]
shoul be fixed now the official release will have to wait a little bit but you can download the github version to solve the problem
