### ISSUE TITLE
Problems removing Activity and Disscussion widgets in groups

### ISSUE THREAD

**Issue by insideth** [ColdTrick/group_tools#79]
If I remove these widgets, when I edit the group widgets are enabled by itself. Sometimes are duplicated in the group dashboard if I edit the group again. 

I´m with Elgg 1.9.8 and Widget Manager 5.0. I´ve tested with all 3rd party plugins disabled except Widget Manager, and Group Tools, so I think is a incompatibility with these plugins.

No problem with all other widgets.

![image](https://cloud.githubusercontent.com/assets/6679837/6233187/84c5d9ae-b6d1-11e4-9dc3-bbe87c1d2f62.png)

**Comment by jdalsem** [comment]
It is a feature of group_tools that widgets that are related to a speficic 'tool' get activated when saving the group. Currently we have no way to determine if a widget is 'removed'. Maybe in the future we will reconsider this feature as it can be percieved as annoying.
