### ISSUE TITLE
Deprecated in 1.1: The view output/confirmlink has been deprecated, please use output/url

### ISSUE THREAD

**Issue by digger149** [ColdTrick/group_tools#81]
Running latest versions of elgg (Release - 1.10.1, Version - 2014130300) and group tools (from github) on bootstrap.

The message:
WARNING: Deprecated in 1.1: The view output/confirmlink has been deprecated, please use output/url Called from [#12] /home/sites/xxxx/public_html/engine/classes/Elgg/ViewsService.php:364

Appears on front-end when editing group

**Comment by jdalsem** [comment]
should be fixed by #83
