### ISSUE TITLE
Thumbnails disappear after migration from 1.8 to 1.9

### ISSUE THREAD

**Issue by gerard-kanters** [ColdTrick/group_tools#82]
When upgrading a site the thumbnails disappear (elgg 1.9.8 from 1.8.19)

See details on this in the community https://community.elgg.org/plugins/736791/releases/3.1

**Comment by jdalsem** [comment]
Gerard, can you test with the latest github version? (you need to update to Elgg 1.10.x to be able to use it)

**Comment by gerard-kanters** [comment]
I just upgraded yesterday to 1.10.4 on my dev server with a copy of a live database. Still no icons unfortunately.

I can circumvent this, by adding this plugin hook in another plugin.

function group_icon_url_override($hook, $type, $returnvalue, $params) {

        $group = $params['entity'];
        $size = $params['size'];

        $icontime = $group->icontime;
        if (null === $icontime) {
                $file = new ElggFile();
                $file->owner_guid = $group->owner_guid;
                $file->setFilename("groups/" . $group->guid . "large.jpg");
                $icontime = $file->exists() ? time() : 0;
                create_metadata($group->guid, 'icontime', $icontime, 'integer', $group->owner_guid, ACCESS_PUBLIC);
        }
        if ($icontime) {
                // return thumbnail
                return "groupicon/$group->guid/$size/$group->name.jpg";
        }

        return "mod/groups/graphics/default{$size}.gif";
}
 
Removing the hook in group_tools also works but requires me to change the plugin, which I do not prefer. 

Why is the plugin hook introduced. Is it still useful ?

**Comment by jeabakker** [comment]
i think this only happens on installations which upgraded from Elgg 1.7 to current and only for groups which haven't been access in Elgg 1.8.

reason
In Elgg 1.7 icontime was not set when saving an icon, in Elgg 1.8 they didn't want to write an upgrade script which corrected this problem for all groups but instead did in only when icons were accessed.

In Elgg 1.9 group_tools took over the icon url and didn't implement this part of the legacy code. I'll implement the legacy code for waybackwards compatibility ;)

**Comment by jeabakker** [comment]
updated the 1.9+ versions

**Comment by jdalsem** [comment]
Is this change sufficient? @gerard-kanters

**Comment by gerard-kanters** [comment]
Yes, thanks  guys !
