### ISSUE TITLE
Using Group Tools Master adding Icon causes depeciated error in 1.10.3.

### ISSUE THREAD

**Issue by Westlake56** [ColdTrick/group_tools#84]
One of the comments for 1.9 mentioned a fix was in the Group Tools Master here so I downloaded and installed it after removing the one for 1.9.

When adding a group icon it gets added but generates a depreciated error to 1.9.

![group tools icon error](https://cloud.githubusercontent.com/assets/11148775/6750578/4ae9ccc2-ced2-11e4-956e-ab4226084cc3.png)

**Comment by jdalsem** [comment]
Fixed. Thanks for reporting
