### ISSUE TITLE
Accessibility of group content

### ISSUE THREAD

**Issue by buraddo** [ColdTrick/group_tools#87]
Is there a reason why "Accessibility of group content" of forced to "Members only" when "Who can see this group?" is set to "Members only". Can't a "Members only" group also have the option to over-ride content restrictions.

Seems to me that there is a precedent for "Who can see this group" as a decision on whether content can be browsed. Many sites now have direct access capability for content via URL for content that is not browsable.

My personal use of the configuration is to have content which is accessible to group members without login. They get the URL in notifications, but are not requires to login to access. They can also forward this to non-members and provide access.

Does having the functionality break the security paradigm of Elgg content.

Brad

**Comment by jdalsem** [comment]
Brad, it is indeed part of Elgg's security paradigm that "hidden" groups can not support more public content. If you need this kind of feature please report a feature request on https://github.com/Elgg/Elgg/issues
