### ISSUE TITLE
elgg_default_access = 0 in elgg_private_settings

### ISSUE THREAD

**Issue by buraddo** [ColdTrick/group_tools#88]
When you set Logged_In_Users as the group setting for "Who can see this group" it creates an entry in elgg_private_settings as elgg_default_access = 0.

This then causes the default content access for new content to be "Private" instead of "Group: XXXX"

Even when the group_tools plugin settings say default access is "Group Members"

This is V3.2 Group_Tools on Elgg 1.9.7..

**Comment by jdalsem** [comment]
Best is to update to a newer version of the group tools plugin. 4.0 has a fix related to the group default access...
