### ISSUE TITLE
Group icon is not displayed

### ISSUE THREAD

**Issue by Yaco** [ColdTrick/group_tools#93]
I am using Elgg 1.12.4. Plugin works fine, but the group icons thumbnails aren't displayed.

When I try to open the icon image url like:

```
/mod/group_tools/pages/groups/thumbnail.php?group_guid=6661&guid=75&size=large&icontime=1449165480
```

I got the error

```
403 Forbidden
```

Could you help me? Thanks in advance!

**Comment by jeabakker** [comment]
there is no 403 header in the thumbnail code.

Is the plugin uploaded correctly (check if the file `/mod/group_tools/pages/groups/thumbnail.php` exists)?

**Comment by lyhkop** [comment]
I am using Elgg 2.0. Group icons thumbnails aren't displayed too!
/mod/group_tools/pages/groups/thumbnail.php is existed.
Thanks for your help!

**Comment by jeabakker** [comment]
the plugin hasn't been tested/redone for 2.0 so this could be the issue. give us a little bit more time. I'm currently preparing to start testing on 2.0

**Comment by lyhkop** [comment]
Thanks for your prompt reply! I think the path of "setting.php" has changed! I changed this path in  /mod/group_tools/pages/groups/thumbnail.php. Now the Group icon can be displayed!
