### ISSUE TITLE
Icons don't shown on group-page

### ISSUE THREAD

**Issue by lweddewer** [ColdTrick/group_tools#94]
When using group-tools the group icon is no shown on the group-page.

Affected versions:
Grouptools 6.0.1 for Elgg Version 1.12.8
Grouptools 7.0-rc.1 for Elgg Version 2.0.2

Doublechecking with Grouptools 5.0 on Elgg Version 1.12.8 shows that this Grouptools Version isn't affected.

I have checked it with turning of any non-bundled plugin in my test-installation. Still the same issue.

Regards
Lothar

**Comment by jeabakker** [comment]
do you have any more information (for example some errors from the error-log) as i can't seam to reproduce the error on my development environment

**Comment by lweddewer** [comment]
Hi jeabakker,

don't found an log relating to the group_tools.
Have done some investions with the Firefox-webconsole

ICON-code without group-tools:
<img src="https://www.ssl-id.de/elggtest.weddewer.de/groupicon/1142/large/1457419295.jpg" alt="Testgruppe 3">

Code with group-tools (no other changes):
<img src="https://www.ssl-id.de/elggtest.weddewer.de/mod/group_tools/pages/groups/thumbnail.php?group_guid=1142&amp;guid=51&amp;size=large&amp;icontime=1457419295" alt="Testgruppe 3">

The webconsole gives a "Could'nt load grafik" when I point on the link.

I upload the grafik when the group-tools was enabled.

Regards
Lothar

**Comment by jeabakker** [comment]
what is the response (http) code for the group_tools link? 404 or 50x or something else?

**Comment by lweddewer** [comment]
Found the code which causes my issue:
It's a Header-line in the file thumbnail.php. 
It works after I comment the line out.

> 	
	header('Content-type: image/jpeg');
	header('Expires: ' . gmdate('D, d M Y H:i:s \G\M\T', strtotime('+6 months')), true);
	header('Pragma: public');
	header('Cache-Control: public');
//	header('Content-Length: $filesize');
	header("ETag: \"{$etag}\"");
        
	echo $filecontents;

I use  webhosting. So it may be an problem of the hoster.

**Comment by jeabakker** [comment]
i see the error in the code
now:
```php
header('Content-Length: $filesize');
```
should be

```php
header("Content-Length: {$filesize}");
```
