### ISSUE TITLE
Non admin users see blank page when clicking Group Invitations

### ISSUE THREAD

**Issue by tempest-kitty** [ColdTrick/group_tools#99]
non admin users being taken to a blank page when they click the "Group Invitation" link on the side bar when they have been invited to a new group. 
As an admin user this function seems to work fine for me, but a normal level user only sees a blank page.

**Comment by jeabakker** [comment]
I'm unable to reproduce the error. Do you have some more information? Like an error in the error_log of the webserver?

**Comment by tempest-kitty** [comment]
I figured it out try this- 
Make a group
Set the Group Membership permission to closed
set the Who can see this group  to Group Members Only

then invite a non Admin user to that group. When they click Groups and then Group Invitations a blank page is displayed. 

However when you set the "Who can see this group" permission to "Logged in users" and invite they normal user can view the invitation fine.

**Comment by jeabakker** [comment]
thanks for the information. I fixed it

**Comment by tempest-kitty** [comment]
^.^ welcome!
